// AUTO-AUTHORED CONTENT — open-source, public-source material only.
// Photographs are copied from Wikimedia Commons with author + licence recorded.
//
// Entries for blocks filled after the first release live in ./items/<block>.ts
// and are concatenated below; this file keeps the original four blocks inline.
import { aircraft } from "@/content/items/aircraft";
import { airDefence } from "@/content/items/air-defence";
import { apc } from "@/content/items/apc";
import { artillery } from "@/content/items/artillery";
import { c2 } from "@/content/items/c2";
import { drones } from "@/content/items/drones";
import { engineering } from "@/content/items/engineering";
import { ew } from "@/content/items/ew";
import { heavyWeapons } from "@/content/items/heavy-weapons";
import { ifv } from "@/content/items/ifv";
import { lightVehicles } from "@/content/items/light-vehicles";
import { radars } from "@/content/items/radars";
import { recon } from "@/content/items/recon";
import { submarines } from "@/content/items/submarines";
import { trucks } from "@/content/items/trucks";
import { vessels } from "@/content/items/vessels";
import type { Block, Item } from "@/content/types";

export type { Block, Item } from "@/content/types";
export const blocks: Block[] = [
  {
    slug: "foundations",
    ordinal: 0,
    title: "Foundations",
    subtitle: "Recognition vocabulary before nation-specific study",
    brief:
      "Before you can identify a specific vehicle you need the categories. This block defines the major classes of military hardware, what each is actually for, and where it sits in a modern force. Learn to read a machine by role first — tracked or wheeled, gun or missile, crewed or remote — then narrow to the exact type.",
    doctrineNote:
      "Grau & Bartles describe the Russian force as an artillery army with a manoeuvre component. Keep that in mind: the classes you meet here are not equal in weight — fires and reconnaissance dominate the structure that the tanks and infantry manoeuvre inside.",
    status: "ready",
  },
  {
    slug: "ranks",
    ordinal: 1,
    title: "Ranks",
    subtitle: "Ground, naval and aerospace rank ladders",
    brief:
      "Rank tells you who you are looking at and what they command. The Russian system runs an enlisted ladder, a warrant tier, junior/senior officer tiers and a general tier. Aerospace Forces use the ground ladder; the Navy runs a parallel naval one.",
    doctrineNote:
      "Command echelon matters more than the title. A podpolkovnik commanding a battalion tactical grouping holds real combined-arms authority; the equivalent staff officer does not.",
    status: "ready",
    ordered: true,
    imageFit: "contain",
  },
  {
    slug: "handguns",
    ordinal: 2,
    title: "Handguns",
    subtitle: "Sidearms of the ground forces and special units",
    brief:
      "Sidearms are secondary weapons carried by officers, crews, and specialists. Recognition rests on slide profile, grip rake, magazine capacity and whether the pistol is a service pistol or a special-purpose weapon.",
    doctrineNote:
      "Pistols are status and last-resort weapons. Their real diagnostic value is the carrier: a suppressed PSS in an image implies special-purpose reconnaissance, not a motor rifle squad.",
    status: "ready",
  },
  {
    slug: "heavy-weapons",
    ordinal: 3,
    title: "Heavy, Squad and Specialized Weapons",
    subtitle: "Machine guns, grenade launchers, ATGMs, flame systems",
    brief:
      "Everything the infantry carries that is heavier than a rifle and lighter than a gun battery. Recognition here rests on mount, feed and tube diameter rather than overall silhouette: a belt from the side and a heavy barrel means a machine gun, a drum and a stubby barrel means an automatic grenade launcher, a flared cone means a recoilless launcher. Learn which weapon sits at which echelon — that is what tells you the size of the force you are looking at.",
    doctrineNote:
      "These are suppression weapons, not killing weapons. Grau & Bartles describe Russian infantry using organic automatic fire to fix an enemy in place so that artillery can destroy it; the crew-served layer exists to hold the enemy still.",
    status: "ready",
  },
  {
    slug: "light-vehicles",
    ordinal: 4,
    title: "Light Vehicles",
    subtitle: "Tigr, Rys, UAZ and protected mobility",
    brief:
      "Everything wheeled below the APC. The first split is protection: a slab-sided hull with small thick windows set high in the doors is armoured, while large glass and a canvas top is not. The second is size — count axles and look at ride height, since a Typhoon towers over a Tigr and a UAZ is smaller again. What a vehicle carries matters less here than who is riding in it.",
    doctrineNote:
      "These are reconnaissance, command and liaison vehicles, not assault transport. Grau & Bartles stress the weight of effort Russian formations put into reconnaissance; much of that effort rides in a Tigr, so identifying one forward says something about intent.",
    status: "ready",
  },
  {
    slug: "trucks",
    ordinal: 5,
    title: "Trucks",
    subtitle: "Ural, KamAZ, KrAZ and logistics chassis",
    brief:
      "The chassis that carries everything else. Recognition runs on three questions: how many axles, is there a bonnet ahead of the cab or does the cab sit over the engine, and what is on the load bed. The last one matters most — the same KamAZ cab appears under cargo, a command post, an EW cabin and a radar shelter, so the truck alone never identifies the system.",
    doctrineNote:
      "Grau & Bartles note that Russian formations carry limited organic lift and lean heavily on rail. The truck park is therefore a real constraint on how far from a railhead a force can fight, which makes counting logistics vehicles a way of estimating reach.",
    status: "ready",
  },
  {
    slug: "artillery",
    ordinal: 6,
    title: "Artillery and Reactive Artillery",
    subtitle: "Towed, self-propelled and MLRS",
    brief:
      "The arm the rest of the force is built around. Three shapes to separate first: a towed gun sits on trails and has no engine, a self-propelled gun is a turret on tracks, and a rocket launcher is a block of tubes on whatever chassis will carry it. After that the questions are narrow — how many trail legs, where the turret sits on the hull, how many tubes and how fat. Calibre follows from the answer rather than being read directly.",
    doctrineNote:
      "Grau & Bartles describe an artillery-led system: manoeuvre units find and fix the enemy so the guns can destroy him, which inverts the Western habit of treating artillery as support. Identifying a battery therefore tells you more about a formation's intent than counting its tanks does.",
    status: "ready",
  },
  {
    slug: "ifv",
    ordinal: 7,
    title: "IFVs",
    subtitle: "BMP and BMD families",
    brief:
      "Tracked vehicles that carry infantry and fight alongside them. Two families, and the split is size: a BMP has six roadwheels, a BMD has five and is airborne. Within each family the gun does the work — a short fat 73 mm means BMP-1, a long thin 30 mm means BMP-2, and both together in one turret means BMP-3 or BMD-4M. Where the engine sits is the one structural difference worth knowing.",
    doctrineNote:
      "The distinction from an APC is doctrinal, not cosmetic. An IFV is meant to fight while its infantry are still aboard, which is why it carries a cannon and missiles; the vehicle is part of the assault rather than the taxi that delivered it.",
    status: "ready",
  },
  {
    slug: "apc",
    ordinal: 8,
    title: "APCs",
    subtitle: "BTR family and tracked carriers",
    brief:
      "Carriers, not fighting vehicles. The wheeled BTR line all looks alike at distance — eight wheels, boat hull, small turret — so recognition comes down to two details: whether there is a proper side door and what is in the turret. No door means BTR-60, small hatches mean BTR-70, a big two-part door means BTR-80, and a long thin barrel above that door means BTR-82A. The tracked carriers are separated by how low they sit.",
    doctrineNote:
      "These deliver infantry and then get out of the way. Grau & Bartles note that Russian motor rifle units expect to dismount close in; the carrier's job is to survive the approach, not the assault, which is why its armament is defensive.",
    status: "ready",
  },
  {
    slug: "tanks",
    ordinal: 9,
    title: "Tanks",
    subtitle: "Main battle tanks in Russian service",
    brief:
      "Three families dominate: T-72 (and its T-90 descendant), T-80 with a gas-turbine engine, and reactivated T-62/T-55 stock. All use a 125 mm smoothbore with an autoloader and a three-man crew except the T-62 (115 mm, four crew). Recognition works off turret shape, ERA pattern, roadwheel spacing and exhaust position.",
    doctrineNote:
      "Tanks are not the centre of the Russian system; they are the shock element inside an artillery-led battle. Grau & Bartles stress that Russian tank sub-units manoeuvre to exploit fires, not to seek tank duels.",
    status: "ready",
  },
  {
    slug: "ew",
    ordinal: 10,
    title: "EW Systems",
    subtitle: "Jamming, direction finding and protection",
    brief:
      "The chassis stops helping here. These ride on the same KamAZ, BAZ, BTR-80 and MT-LB hulls learned in earlier blocks, so the antenna is the whole recognition problem: one dish or several, an open lattice or a solid panel, on the roof or guyed out across the field beside it. Footprint is the second cue — a jammer reaching hundreds of kilometres spreads masts and guy wires over open ground, while one protecting its own vehicle keeps everything on the roof.",
    doctrineNote:
      "Grau & Bartles treat radio-electronic combat as an arm in its own right, organic down to brigade rather than attached from above. Its purpose is to break the link between the enemy's sensors and his guns — the same link the Russian system depends on for itself.",
    status: "ready",
    imageFit: "contain",
  },
  {
    slug: "c2",
    ordinal: 11,
    title: "C2 Systems",
    subtitle: "Command posts, Strelets, ACCS",
    brief:
      "Command vehicles are built to be unremarkable, so recognition works by subtraction: a hull you already know, with the weapon missing and antennas in its place. What separates them is the chassis, and the chassis follows the echelon — a box-bodied truck well to the rear, a wheeled carrier with the manoeuvre units, a tracked hull that can follow the assault, and at the bottom a handheld terminal in a trench.",
    doctrineNote:
      "Finding the command post is how you paralyse an artillery-led force, and both sides know it. Everything here is shaped by that: the vehicles hide inside ordinary columns, and the most important node in the chain is a device in an observer's hands rather than anything with armour.",
    status: "ready",
  },
  {
    slug: "radars",
    ordinal: 12,
    title: "Radars",
    subtitle: "Surveillance, counter-battery and target acquisition",
    brief:
      "Read the antenna and you have the radar. Size runs with wavelength and with range: a lattice of long rods spanning two lorry-widths is a metre-band set searching hundreds of kilometres for aircraft, while a small drum on a tracked hull is looking a few kilometres for vehicles or shells. Then ask what it hunts — air surveillance sets stand high on masts and turn full circle, battlefield and counter-battery sets sit low and scan a narrow sector.",
    doctrineNote:
      "The counter-battery sets are the ones that matter most here. They track a shell in flight and compute backwards to the gun, which makes them among the most valuable targets on a battlefield where artillery decides the outcome — hence tracked, low, and moved as soon as they have radiated.",
    status: "ready",
    imageFit: "contain",
  },
  {
    slug: "engineering",
    ordinal: 13,
    title: "Engineering Vehicles",
    subtitle: "Bridging, mine clearing, earthmoving",
    brief:
      "Almost everything here is a tank hull with the turret taken off and a tool put in its place, so recognition means reading the tool: a jointed arm, a dozer blade, a folded bridge, a hinged launcher cover, a chute at the back. Where the tool is a bridge, ask what carries it — a tank hull goes where tanks go, a truck follows the road. The first cue of all is that none of them can fight.",
    doctrineNote:
      "Mobility is treated as a combat function rather than a support one. River crossing in particular is a planned set-piece, so a pontoon column moving forward is among the clearest indicators of intent a formation gives away.",
    status: "ready",
  },
  {
    slug: "air-defence",
    ordinal: 14,
    title: "Air Defence Systems",
    subtitle: "SHORAD to strategic SAM",
    brief:
      "One question separates most of this block: guns, missiles, or both. Then read the launcher. Missiles in sealed box canisters, or hidden entirely inside the turret, belong to short-range systems riding with the manoeuvre units; missiles carried openly on rails, or raised as large tubes, belong to the long-range systems standing behind them. Size tracks reach almost perfectly, so the ladder from a tracked gun carriage to an 8x8 with four erected canisters is also the ladder from two kilometres to four hundred.",
    doctrineNote:
      "Russian air defence is layered rather than centralised: each echelon carries its own cover, so a formation sits under several systems with overlapping reach rather than one. Identifying which layer you are looking at tells you which echelon owns the ground.",
    status: "ready",
  },
  {
    slug: "reconnaissance",
    ordinal: 15,
    title: "Reconnaissance Systems",
    subtitle: "Ground, artillery and special reconnaissance",
    brief:
      "Reconnaissance vehicles look like the fighting vehicles they are built from, because they have to survive where they are sent. The tell is always on the roof: a sensor where a weapon should be, an extra cupola, a folded radar, a cluster of antennas. This is a short block by design — the radars in block 12, the observation parties in block 11 and the drones in block 18 do much of the same work and are covered there.",
    doctrineNote:
      "Grau & Bartles describe reconnaissance as the front half of a reconnaissance-fires system rather than an end in itself: its product is a target for the guns. That is why the artillery's own reconnaissance vehicle is a higher-value objective than most tanks.",
    status: "ready",
  },
  {
    slug: "vessels",
    ordinal: 16,
    title: "Warships and Vessels",
    subtitle: "Surface combatants, patrol and auxiliary",
    brief:
      "Ships are read by profile: length against anything nearby, where the superstructure sits, and what stands on the deck. Missile ships show their armament — huge tubes angled along the sides on the older designs, flush vertical hatches on the newer ones — so deck layout separates the classes long before hull shape does. A blunt bow and a superstructure pushed right aft means a landing ship rather than a combatant.",
    doctrineNote:
      "Russian surface strength is concentrated in very few large hulls and a great many small ones. Because the small missile ships carry the same land-attack weapons as the large ones, size is a poor guide to reach — which is the single most useful thing to know when identifying them.",
    status: "ready",
    imageFit: "contain",
  },
  {
    slug: "submarines",
    ordinal: 17,
    title: "Submarines",
    subtitle: "SSN, SSK, SSGN and SSBN",
    brief:
      "Only three things are ever visible: hull length, beam, and the shape and position of the sail — and that is enough. Ballistic missile boats carry their tubes behind the sail, raising a long hump down the after casing. Cruise missile boats carry theirs outside the pressure hull, which makes the boat unusually wide with no hump. Attack boats have neither and look clean.",
    doctrineNote:
      "The submarine force holds the survivable part of the nuclear deterrent and the main threat to surface groups, so it absorbs a disproportionate share of naval investment. Recognition here is about class rather than individual boat, because a class defines the weapon it carries.",
    status: "ready",
    imageFit: "contain",
  },
  {
    slug: "drones",
    ordinal: 18,
    title: "Drones",
    subtitle: "Air, ground and surface unmanned systems",
    brief:
      "Sort by purpose and the size follows. A small catapult-launched airframe is looking for targets for the guns; a large twin-boom or single-fuselage aircraft is watching an area for hours and may be armed; something small with cruciform wings and no landing gear is a munition rather than an aircraft. Ground robots are recognised the other way round — a tracked vehicle with no hatches, no vision blocks and no room for anyone inside.",
    doctrineNote:
      "Drones are what now close the reconnaissance-fires loop that the whole Russian system is built around. Grau & Bartles argue Russian artillery is only ever as good as its observation, and observation has largely moved from the vehicles in block 15 to the airframes here.",
    status: "ready",
  },
  {
    slug: "aircraft",
    ordinal: 19,
    title: "Warplanes",
    subtitle: "Fighter, interceptor, bomber, transport",
    brief:
      "Count the engines, then read the wing. One straight wing over two body-side engines is an attack aircraft; two engines under a swept wing with twin fins is a fighter; four engines is a bomber or a transport, and the tail says which. The fine separations come last, because the Flanker family is one airframe stretched into several aircraft and only the nose reliably tells them apart.",
    doctrineNote:
      "Russian air power is used to reach what the guns cannot rather than to win the battle on its own. That is why the strike aircraft outnumber the interceptors, why the bombers are missile carriers that never enter defended airspace, and why the transport fleet decides what the airborne forces can actually do.",
    status: "ready",
    imageFit: "contain",
  },
];

const baseItems: Item[] = [
  {
    slug: "concept-mbt",
    blockSlug: "foundations",
    name: "Main Battle Tank (MBT)",
    aka: "OBT (osnovnoy boyevoy)",
    imageUrl: "/images/items/concept-mbt.jpg",
    imageCredit: "CC BY 4.0 — Vyacheslav Argenberg",
    imagePage:
      "https://commons.wikimedia.org/wiki/File:Moscow_2012_Victory_Day_Parade_Rehearsal,_T-90_tank,_Russia.jpg",
    armament: "Large-calibre high-velocity gun in a fully rotating turret, coaxial machine gun",
    rangeText: "Gun engagement typically 2,000–3,000 m",
    cues: [
      "Tracks, not wheels",
      "Single large gun in a 360° turret",
      "Thick sloped or block-shaped applique armour",
      "Low hull relative to width",
    ],
    placements: [
      "Tank battalions of tank and motor rifle brigades/regiments",
      "Tank companies attached to combined-arms battalions",
    ],
    doctrineNote:
      "The tank is the protected direct-fire punch of a combined-arms grouping. It moves after artillery has suppressed the objective.",
    crew: "3–4",
    service: "Class",
    sort: 0,
  },
  {
    slug: "concept-ifv",
    blockSlug: "foundations",
    name: "Infantry Fighting Vehicle (IFV)",
    aka: "BMP class",
    imageUrl: "/images/items/concept-ifv.jpg",
    imageCredit: "CC BY-SA 3.0 — Vitaliy Ragulin",
    imagePage:
      "https://commons.wikimedia.org/wiki/File:BMP-3_amphibious_infantry_fighting_vehicle.jpg",
    armament: "Autocannon (usually 30 mm), ATGM, coaxial MG",
    rangeText: "Autocannon 2,000–4,000 m; ATGM 4,000–5,500 m",
    cues: [
      "Carries dismounts AND fights: cannon plus firing ports/rear doors",
      "Turret is small relative to hull",
      "Usually tracked and amphibious",
      "Thin armour compared with a tank",
    ],
    placements: [
      "Motor rifle companies of BMP-equipped battalions",
      "Air assault (VDV) units use the BMD family",
    ],
    doctrineNote:
      "An IFV delivers the squad onto the objective and then supports it with cannon fire. It is not a light tank.",
    crew: "3 + 7–8 dismounts",
    service: "Class",
    sort: 1,
  },
  {
    slug: "concept-apc",
    blockSlug: "foundations",
    name: "Armoured Personnel Carrier (APC)",
    aka: "BTR class",
    imageUrl: "/images/items/concept-apc.jpg",
    imageCredit: "CC BY 4.0 — Ministry of Defence of the Russian Federation",
    imagePage: "https://commons.wikimedia.org/wiki/File:BTR-80_and_BTR-82A_with_RP-377_jammer.jpg",
    armament: "Heavy machine gun or light autocannon in a small turret",
    rangeText: "MG 1,500–2,000 m; 30 mm to 4,000 m",
    cues: [
      "Usually 8x8 wheeled with evenly spaced wheels",
      "Boat-shaped amphibious hull",
      "Small turret, no ATGM",
      "Side hatches rather than a large rear ramp",
    ],
    placements: [
      "Motor rifle companies of BTR-equipped battalions",
      "Used widely by naval infantry and internal troops",
    ],
    doctrineNote:
      "The APC is a battlefield taxi with protection; its firepower supports dismounts rather than leading the assault.",
    crew: "3 + 7 dismounts",
    service: "Class",
    sort: 2,
  },
  {
    slug: "concept-spg",
    blockSlug: "foundations",
    name: "Self-Propelled Gun (SPG)",
    aka: "SAU (samokhodnaya artilleriyskaya ustanovka)",
    imageUrl: "/images/items/concept-spg.jpg",
    imageCredit: "CC BY-SA 4.0 — Zala",
    imagePage: "https://commons.wikimedia.org/wiki/File:2S19_Msta-S_PM_MWB_03.jpg",
    armament: "152 mm howitzer",
    rangeText: "Conventional 24–29 km; rocket-assisted to ~40 km",
    cues: [
      "Very large turret with a long barrel and muzzle brake",
      "Tracked chassis, tall boxy hull",
      "Barrel usually travels locked over the rear deck",
      "No ERA blocks",
    ],
    placements: [
      "Self-propelled artillery battalions of brigades and divisions",
      "Artillery brigades of combined-arms armies",
    ],
    doctrineNote:
      "Grau & Bartles: fires are the primary killing system. The SPG battalion, not the tank company, is the main effort in most Russian tactical actions.",
    crew: "4–5",
    service: "Class",
    sort: 3,
  },
  {
    slug: "concept-mlrs",
    blockSlug: "foundations",
    name: "Multiple Launch Rocket System (MLRS)",
    aka: "Reactive artillery",
    imageUrl: "/images/items/concept-mlrs.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:BM-21_Grad_(2).jpg",
    armament: "Rocket pack of 12–40 tubes",
    rangeText: "20–40 km (122 mm); up to 70–90 km (larger calibres)",
    cues: [
      "Tube or rail pack on a truck chassis",
      "No turret, no armour",
      "Blast shields over the cab",
      "Elevating launcher assembly",
    ],
    placements: ["Rocket artillery battalions of brigades", "Army-level rocket artillery brigades"],
    doctrineNote:
      "Massed area fire for suppression and minelaying, delivered fast and then displaced to avoid counter-battery.",
    crew: "3",
    service: "Class",
    sort: 4,
  },
  {
    slug: "concept-sam",
    blockSlug: "foundations",
    name: "Surface-to-Air Missile System (SAM)",
    aka: "ZRK (zenitny raketny kompleks)",
    imageUrl: "/images/items/concept-sam.jpg",
    imageCredit: "CC BY-SA 4.0 — Mike1979 Russia",
    imagePage:
      "https://commons.wikimedia.org/wiki/File:51P6_launcher_S-400_Triumf_Army-2022_2022-08-20_2416.jpg",
    armament: "Vertical or inclined missile canisters, radar guidance",
    rangeText: "SHORAD 10–20 km; long range 200–400 km",
    cues: [
      "Large canister tubes rather than a gun",
      "Separate radar vehicles nearby",
      "Erecting launcher on a heavy truck or tracked chassis",
      "Cable runs and generator sets in position",
    ],
    placements: [
      "Air defence battalions organic to manoeuvre brigades",
      "Aerospace Forces regiments for strategic systems",
    ],
    doctrineNote:
      "Layered air defence is treated as a manoeuvre enabler: it buys the ground force freedom to mass.",
    crew: "3–4",
    service: "Class",
    sort: 5,
  },
  {
    slug: "concept-ship",
    blockSlug: "foundations",
    name: "Surface Combatant",
    aka: "Frigate / corvette / destroyer",
    imageUrl: "/images/items/concept-ship.jpg",
    imageCredit: "CC BY 4.0 — Ministry of Defence of the Russian Federation",
    imagePage: "https://commons.wikimedia.org/wiki/File:Admiral_Gorshkov_frigate_03.jpg",
    armament: "Naval gun, vertical launch cells, close-in weapon systems",
    rangeText: "Cruise missiles to 1,500+ km",
    cues: [
      "Single main gun forward of the bridge",
      "Flush VLS hatches on the foredeck",
      "Enclosed mast with panel radar arrays",
      "Helicopter deck aft on larger units",
    ],
    placements: ["Surface action groups of the four fleets and the Caspian Flotilla"],
    doctrineNote:
      "Modern Russian surface units are valued primarily as mobile launch platforms for long-range precision strike.",
    crew: "Varies",
    service: "Class",
    sort: 6,
  },
  {
    slug: "concept-uav",
    blockSlug: "foundations",
    name: "Unmanned Aerial Vehicle (UAV)",
    aka: "Drone / BLA",
    imageUrl: "/images/items/concept-uav.jpg",
    imageCredit: "CC BY-SA 4.0 — Mike1979 Russia",
    imagePage: "https://commons.wikimedia.org/wiki/File:Orlan-10_UAV_Army-2022_2022-08-20_2287.jpg",
    armament: "Usually unarmed reconnaissance; loitering types carry a warhead",
    rangeText: "Tactical UAV radius 100–120 km",
    cues: [
      "Small airframe, pusher propeller at the rear",
      "High-mounted straight wing",
      "No cockpit glazing",
      "Catapult or hand launch, parachute recovery",
    ],
    placements: ["UAV companies of manoeuvre brigades", "Artillery units for fire correction"],
    doctrineNote:
      "Grau & Bartles highlight the UAV–artillery pairing: the drone is the sensor that closes the reconnaissance-fire loop within minutes.",
    crew: "0 (2–3 operators)",
    service: "Class",
    sort: 7,
  },
  {
    slug: "concept-ew",
    blockSlug: "foundations",
    name: "Electronic Warfare System (EW)",
    aka: "REB",
    imageUrl: "/images/items/concept-ew.jpg",
    imageCredit: "CC BY-SA 4.0 — Boevaya mashina",
    imagePage: "https://commons.wikimedia.org/wiki/File:1RL257E_Krasukha-4_Army-2018.jpg",
    armament: "Non-kinetic: jamming and direction finding",
    rangeText: "Jamming effect 150–300 km for strategic types",
    cues: [
      "Large dish, panel or mast antennas instead of weapons",
      "Heavy truck chassis with a boxy operator cabin",
      "Stabiliser jacks deployed in position",
      "No gun, no missile canisters",
    ],
    placements: ["EW companies of manoeuvre brigades", "Independent EW brigades at army level"],
    doctrineNote:
      "EW protects the force and blinds the enemy's reconnaissance-strike loop; it is treated as fires by other means.",
    crew: "3–4",
    service: "Class",
    sort: 8,
  },
  {
    slug: "concept-recon",
    blockSlug: "foundations",
    name: "Reconnaissance Vehicle",
    aka: "BRM / razvedka",
    imageUrl: "/images/items/concept-recon.jpg",
    imageCredit: "CC BY-SA 4.0 — Mike1979 Russia",
    imagePage:
      "https://commons.wikimedia.org/wiki/File:BRM_with_BTR-80_Weapon_Army-2022_2022-08-20_2621.jpg",
    armament: "Autocannon and MG; primary payload is sensors",
    rangeText: "Sensor detection 10–25 km",
    cues: [
      "Looks like an IFV but carries extra antennas and mast sensors",
      "Fewer dismount hatches",
      "Ground surveillance radar dome or mast",
      "Often paired with UAV teams",
    ],
    placements: [
      "Reconnaissance companies/battalions of brigades",
      "Artillery reconnaissance batteries",
    ],
    doctrineNote:
      "Reconnaissance exists to feed fires. Detection triggers artillery, not a manoeuvre engagement, in most cases.",
    crew: "4–6",
    service: "Class",
    sort: 9,
  },
  {
    slug: "rank-ryadovoy",
    blockSlug: "ranks",
    name: "Ryadovoy",
    aka: "Private",
    imageUrl: "/images/items/rank-ryadovoy.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-1-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Rifleman in a squad. Lowest enlisted rank in the ground and aerospace forces."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 0,
  },
  {
    slug: "rank-yefreytor",
    blockSlug: "ranks",
    name: "Yefreytor",
    aka: "Senior Private / Lance Corporal",
    imageUrl: "/images/items/rank-yefreytor.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-2-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Experienced soldier, often a deputy or specialist within the squad."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 1,
  },
  {
    slug: "rank-mladshiy-serzhant",
    blockSlug: "ranks",
    name: "Mladshiy Serzhant",
    aka: "Junior Sergeant",
    imageUrl: "/images/items/rank-mladshiy-serzhant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-4-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Squad leader or deputy squad leader."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 2,
  },
  {
    slug: "rank-serzhant",
    blockSlug: "ranks",
    name: "Serzhant",
    aka: "Sergeant",
    imageUrl: "/images/items/rank-serzhant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-5-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Squad leader; commands a BMP/BTR crew and its dismounts."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 3,
  },
  {
    slug: "rank-starshiy-serzhant",
    blockSlug: "ranks",
    name: "Starshiy Serzhant",
    aka: "Senior Sergeant",
    imageUrl: "/images/items/rank-starshiy-serzhant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-7-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Deputy platoon leader."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 4,
  },
  {
    slug: "rank-starshina",
    blockSlug: "ranks",
    name: "Starshina",
    aka: "Sergeant Major",
    imageUrl: "/images/items/rank-starshina.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-8-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Senior enlisted of a company; responsible for supply and discipline."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 5,
  },
  {
    slug: "rank-praporshchik",
    blockSlug: "ranks",
    name: "Praporshchik",
    aka: "Warrant Officer",
    imageUrl: "/images/items/rank-praporshchik.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-9a-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Technical and supply specialist; armoury, motor pool, stores."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 6,
  },
  {
    slug: "rank-starshiy-praporshchik",
    blockSlug: "ranks",
    name: "Starshiy Praporshchik",
    aka: "Senior Warrant Officer",
    imageUrl: "/images/items/rank-starshiy-praporshchik.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OR-9b-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Senior technical specialist at battalion level."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 7,
  },
  {
    slug: "rank-mladshiy-leytenant",
    blockSlug: "ranks",
    name: "Mladshiy Leytenant",
    aka: "Junior Lieutenant",
    imageUrl: "/images/items/rank-mladshiy-leytenant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-1a-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Junior platoon leader, usually newly commissioned."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 8,
  },
  {
    slug: "rank-leytenant",
    blockSlug: "ranks",
    name: "Leytenant",
    aka: "Lieutenant",
    imageUrl: "/images/items/rank-leytenant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-1b-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Platoon leader."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 9,
  },
  {
    slug: "rank-starshiy-leytenant",
    blockSlug: "ranks",
    name: "Starshiy Leytenant",
    aka: "Senior Lieutenant",
    imageUrl: "/images/items/rank-starshiy-leytenant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-1c-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Senior platoon leader or company deputy."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 10,
  },
  {
    slug: "rank-kapitan",
    blockSlug: "ranks",
    name: "Kapitan",
    aka: "Captain",
    imageUrl: "/images/items/rank-kapitan.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-2-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Company commander."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 11,
  },
  {
    slug: "rank-mayor",
    blockSlug: "ranks",
    name: "Mayor",
    aka: "Major",
    imageUrl: "/images/items/rank-mayor.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-3-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Battalion deputy commander or staff officer."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 12,
  },
  {
    slug: "rank-podpolkovnik",
    blockSlug: "ranks",
    name: "Podpolkovnik",
    aka: "Lieutenant Colonel",
    imageUrl: "/images/items/rank-podpolkovnik.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-4-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Battalion commander; commands a battalion tactical grouping."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 13,
  },
  {
    slug: "rank-polkovnik",
    blockSlug: "ranks",
    name: "Polkovnik",
    aka: "Colonel",
    imageUrl: "/images/items/rank-polkovnik.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-5-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Regiment or brigade commander."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 14,
  },
  {
    slug: "rank-general-mayor",
    blockSlug: "ranks",
    name: "General-Mayor",
    aka: "Major General",
    imageUrl: "/images/items/rank-general-mayor.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-6-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Division commander or deputy army commander."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 15,
  },
  {
    slug: "rank-general-leytenant",
    blockSlug: "ranks",
    name: "General-Leytenant",
    aka: "Lieutenant General",
    imageUrl: "/images/items/rank-general-leytenant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-7-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Combined-arms army commander."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 16,
  },
  {
    slug: "rank-general-polkovnik",
    blockSlug: "ranks",
    name: "General-Polkovnik",
    aka: "Colonel General",
    imageUrl: "/images/items/rank-general-polkovnik.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Army-OF-8-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Military district / grouping of forces commander."],
    placements: ["Ground Forces / Aerospace Forces rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 17,
  },
  {
    slug: "rank-navy-matros",
    blockSlug: "ranks",
    name: "Matros",
    aka: "Seaman",
    imageUrl: "/images/items/rank-navy-matros.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OR-1-1994-everyday.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Ryadovoy."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 100,
  },
  {
    slug: "rank-navy-starshina-2-stati",
    blockSlug: "ranks",
    name: "Starshina 2 stati",
    aka: "Petty Officer 2nd Class",
    imageUrl: "/images/items/rank-navy-starshina-2-stati.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OR-4-1994-everyday.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Junior Sergeant."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 101,
  },
  {
    slug: "rank-navy-michman",
    blockSlug: "ranks",
    name: "Michman",
    aka: "Warrant Officer (Navy)",
    imageUrl: "/images/items/rank-navy-michman.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OR-9a-1994-everyday.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Praporshchik."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 102,
  },
  {
    slug: "rank-navy-kapitan-leytenant",
    blockSlug: "ranks",
    name: "Kapitan-Leytenant",
    aka: "Lieutenant Captain",
    imageUrl: "/images/items/rank-navy-kapitan-leytenant.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-2-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Major; department head on a warship."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 103,
  },
  {
    slug: "rank-navy-kapitan-3-ranga",
    blockSlug: "ranks",
    name: "Kapitan 3 ranga",
    aka: "Captain 3rd Rank",
    imageUrl: "/images/items/rank-navy-kapitan-3-ranga.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-3-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Lieutenant Colonel; commands a corvette."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 104,
  },
  {
    slug: "rank-navy-kapitan-2-ranga",
    blockSlug: "ranks",
    name: "Kapitan 2 ranga",
    aka: "Captain 2nd Rank",
    imageUrl: "/images/items/rank-navy-kapitan-2-ranga.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-4-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Colonel; commands a frigate or submarine."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 105,
  },
  {
    slug: "rank-navy-kapitan-1-ranga",
    blockSlug: "ranks",
    name: "Kapitan 1 ranga",
    aka: "Captain 1st Rank",
    imageUrl: "/images/items/rank-navy-kapitan-1-ranga.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-5-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Commands a major surface combatant or SSBN."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 106,
  },
  {
    slug: "rank-navy-kontr-admiral",
    blockSlug: "ranks",
    name: "Kontr-Admiral",
    aka: "Rear Admiral",
    imageUrl: "/images/items/rank-navy-kontr-admiral.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-6-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Major General; commands a flotilla."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 107,
  },
  {
    slug: "rank-navy-vitse-admiral",
    blockSlug: "ranks",
    name: "Vitse-Admiral",
    aka: "Vice Admiral",
    imageUrl: "/images/items/rank-navy-vitse-admiral.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-7-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Naval equivalent of Lieutenant General; fleet deputy commander."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 108,
  },
  {
    slug: "rank-navy-admiral",
    blockSlug: "ranks",
    name: "Admiral",
    aka: null,
    imageUrl: "/images/items/rank-navy-admiral.png",
    imageCredit: "CC BY-SA 4.0 — Skjoldbro",
    imagePage: "https://commons.wikimedia.org/wiki/File:Russia-Navy-OF-8-2010.svg",
    armament: null,
    rangeText: null,
    cues: ["Fleet commander."],
    placements: ["Navy rank ladder"],
    doctrineNote: null,
    crew: null,
    service: "Rank",
    sort: 109,
  },
  {
    slug: "pm",
    blockSlug: "handguns",
    name: "PM (Makarov)",
    aka: "Pistolet Makarova, 9x18 mm",
    imageUrl: "/images/items/pm.jpg",
    imageCredit: "CC BY-SA 4.0 — Tyg728",
    imagePage: "https://commons.wikimedia.org/wiki/File:Makarov_pistol_20181020.jpg",
    armament: "9x18 mm PM, 8-round magazine",
    rangeText: "Effective 50 m",
    cues: [
      "Short slide with a rounded muzzle end",
      "Exposed hammer, small fixed sights",
      "Slide-mounted safety lever",
      "One-piece wrap-around grip with a star or lanyard loop",
    ],
    placements: [
      "Legacy service pistol of officers, crews and rear-echelon personnel",
      "Still widely issued to police and internal troops",
    ],
    doctrineNote:
      "Ubiquitous rather than important. Its presence indicates an older or second-line issue set.",
    crew: "1",
    service: "Legacy, still in service",
    sort: 0,
  },
  {
    slug: "mp-443",
    blockSlug: "handguns",
    name: "MP-443 Grach (PYa)",
    aka: "Pistolet Yarygina, 6P35",
    imageUrl: "/images/items/mp-443.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:9mm_Yarygin_pistol_PYa.jpg",
    armament: "9x19 mm, 17/18-round magazine",
    rangeText: "Effective 50 m",
    cues: [
      "Longer squared slide than the PM",
      "Double-stack grip, visibly thicker",
      "Frame-mounted safety and squared trigger guard",
      "Prominent white-dot three-dot sights",
    ],
    placements: [
      "Standard service pistol of the Armed Forces since 2003",
      "Officers, vehicle crews, specialists",
    ],
    doctrineNote:
      "The intended universal replacement for the PM; its issue marks a modernised unit set.",
    crew: "1",
    service: "Current standard",
    sort: 1,
  },
  {
    slug: "gsh-18",
    blockSlug: "handguns",
    name: "GSh-18",
    aka: "6P54",
    imageUrl: "/images/items/gsh-18.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin allow to use this picture in Copyright Policy",
    imagePage: "https://commons.wikimedia.org/wiki/File:GSh-18_18.jpg",
    armament: "9x19 mm (incl. 7N31 AP), 18-round magazine",
    rangeText: "Effective 50 m",
    cues: [
      "Very light polymer frame, slab-sided slide",
      "No external hammer — striker fired",
      "Distinctive short slide serrations at the rear only",
      "Straight, blocky profile",
    ],
    placements: ["Issued to selected army, MVD and special units alongside the MP-443"],
    doctrineNote: "Fielded for its armour-piercing performance against body armour at close range.",
    crew: "1",
    service: "In service, limited",
    sort: 2,
  },
  {
    slug: "aps",
    blockSlug: "handguns",
    name: "APS (Stechkin)",
    aka: "Avtomaticheskiy Pistolet Stechkina",
    imageUrl: "/images/items/aps.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:Stechkin_APS.jpg",
    armament: "9x18 mm, 20-round magazine, select-fire",
    rangeText: "Effective 50 m (200 m with stock)",
    cues: [
      "Unusually long grip housing a 20-round magazine",
      "Selector lever on the slide",
      "Holster doubles as a shoulder stock",
      "Larger overall than any other Russian service pistol",
    ],
    placements: [
      "Special-purpose and reconnaissance units",
      "Vehicle and artillery crews historically",
    ],
    doctrineNote:
      "A machine pistol used where a compact automatic is wanted — recon teams, protective details.",
    crew: "1",
    service: "Legacy / special use",
    sort: 3,
  },
  {
    slug: "sr-1mp",
    blockSlug: "handguns",
    name: "SR-1MP Gyurza",
    aka: "Vektor / SPS, 6P53",
    imageUrl: "/images/items/sr-1mp.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:SR-1M_pistol_at_Interpolitex-2016_01.jpg",
    armament: "9x21 mm armour-piercing, 18-round magazine",
    rangeText: "Effective 50 m; defeats body armour to 50 m",
    cues: [
      "Modern squared polymer frame with accessory rail",
      "Grip safety on the backstrap",
      "Thick slide with forward serrations",
      "No conventional external safety lever",
    ],
    placements: ["FSB, FSO and army special-purpose (spetsnaz) units"],
    doctrineNote:
      "A defeat-the-vest pistol; presence signals a special-purpose or protective unit rather than line infantry.",
    crew: "1",
    service: "In service, special units",
    sort: 4,
  },
  {
    slug: "pss",
    blockSlug: "handguns",
    name: "PSS Vul",
    aka: "Pistolet Spetsialnyy Samozaryadnyy",
    imageUrl: "/images/items/pss.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:PSS_Silent_Pistol_(543-46).jpg",
    armament: "7.62x42 mm SP-4 captive-piston cartridge, 6 rounds",
    rangeText: "Effective 25 m",
    cues: [
      "No suppressor tube — the pistol looks conventional but is silent",
      "Blocky slab slide, very plain lines",
      "Short barrel with no muzzle protrusion",
      "Small 6-round magazine, slim grip",
    ],
    placements: ["Special-purpose reconnaissance and state security units only"],
    doctrineNote:
      "Silence comes from the cartridge, not a suppressor. Never a general-issue weapon.",
    crew: "1",
    service: "Special units",
    sort: 5,
  },
  {
    slug: "udav",
    blockSlug: "handguns",
    name: "Udav",
    aka: "SR-1 successor, 6P72",
    imageUrl: "/images/items/udav.jpg",
    imageCredit: "CC BY-SA 4.0 — ЦНИИТОЧМАШ",
    imagePage:
      "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B8%D1%81%D1%82%D0%BE%D0%BB%D0%B5%D1%82_%D0%A3%D0%B4%D0%B0%D0%B2.jpg",
    armament: "9x21 mm, 18-round magazine",
    rangeText: "Effective 100 m",
    cues: [
      "Long modern slide with full-length rail",
      "Ambidextrous controls and a reversible magazine release",
      "Squared trigger guard with a finger relief",
      "Suppressor-capable threaded barrel on some units",
    ],
    placements: ["Entering service as the successor to the MP-443 across the Armed Forces"],
    doctrineNote: "Fielding is gradual; its appearance indicates a recently re-equipped unit.",
    crew: "1",
    service: "Entering service",
    sort: 6,
  },
  {
    slug: "t-62m",
    blockSlug: "tanks",
    name: "T-62M",
    aka: "Obyekt 166M",
    imageUrl: "/images/items/t-62m.jpg",
    imageCredit: "CC0 — Nickel nitride",
    imagePage: "https://commons.wikimedia.org/wiki/File:T-62M_-_Army-2023-14.jpg",
    armament: "115 mm U-5TS smoothbore; 12.7 mm NSVT",
    rangeText: "Gun 1,600–2,000 m; Sheksna ATGM 4,000 m",
    cues: [
      "Five roadwheels with a visible wide gap between the 3rd and 4th",
      "Rounded turret with a bulging 'horseshoe' BDD armour block on the front",
      "No autoloader — larger turret bustle absent",
      "115 mm barrel, thinner than the 125 mm family",
    ],
    placements: [
      "Reactivated stocks issued to second-line and territorial formations",
      "Used for direct fire support rather than tank duels",
    ],
    doctrineNote:
      "Reactivated mass. Grau & Bartles' framing applies: quantity restores the artillery-supporting direct-fire component even when quality is dated.",
    crew: "4",
    service: "Reactivated legacy",
    sort: 0,
  },
  {
    slug: "t-72b3",
    blockSlug: "tanks",
    name: "T-72B3",
    aka: "Obr. 2011",
    imageUrl: "/images/items/t-72b3.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:T-72B3_-_TankBiathlon2013-09.jpg",
    armament: "125 mm 2A46M-5 smoothbore, autoloader; 12.7 mm NSVT",
    rangeText: "Gun 2,500–3,000 m; Svir/Refleks ATGM 4,000–5,000 m",
    cues: [
      "Six evenly spaced small roadwheels, no gaps",
      "Rubber side skirts with a distinctive slanted front flap",
      "Sosna-U sight box on the left of the turret roof",
      "Kontakt-1 ERA bricks rather than built-in Relikt panels",
    ],
    placements: ["The most numerous tank in tank battalions of motor rifle and tank brigades"],
    doctrineNote:
      "The workhorse. Any Russian tank battalion is most likely equipped with a T-72B3 variant.",
    crew: "3",
    service: "Current standard",
    sort: 1,
  },
  {
    slug: "t-72b3m",
    blockSlug: "tanks",
    name: "T-72B3M",
    aka: "Obr. 2016 / T-72B3 mod. 2016",
    imageUrl: "/images/items/t-72b3m.jpg",
    imageCredit: "CC BY 4.0 — The Presidential Press and Information Office",
    imagePage: "https://commons.wikimedia.org/wiki/File:2021_Moscow_Victory_Day_Parade_021.jpg",
    armament: "125 mm 2A46M-5; 12.7 mm remote weapon station",
    rangeText: "Gun to 3,000 m; ATGM 5,000 m",
    cues: [
      "Relikt ERA panels replacing Kontakt-1 bricks on hull and turret front",
      "Slat/cage screen over the engine deck and turret rear",
      "Wider, angular side skirts",
      "Heavier commander's sight assembly",
    ],
    placements: ["Modernised tank battalions; first-line tank formations"],
    doctrineNote:
      "The upgrade path, not a new tank: better optics and protection on the same hull.",
    crew: "3",
    service: "Current, modernised",
    sort: 2,
  },
  {
    slug: "t-80u",
    blockSlug: "tanks",
    name: "T-80U",
    aka: "Obyekt 219AS",
    imageUrl: "/images/items/t-80u.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:4thTankBrigade_-_T-80U_-11.jpg",
    armament: "125 mm 2A46M-1; 12.7 mm NSVT",
    rangeText: "Gun 2,500–3,000 m; Refleks ATGM 5,000 m",
    cues: [
      "Gas turbine: broad flat rear deck with a large central exhaust grille",
      "Six roadwheels but a noticeably different, boxier hull rear",
      "Kontakt-5 built-in ERA giving the turret a wedge-faced look",
      "High-pitched turbine whine in video",
    ],
    placements: [
      "Tank units in the Western and Northern operational directions",
      "Formations expected to operate in cold conditions",
    ],
    doctrineNote:
      "The turbine gives sprint mobility at a high fuel cost — a formation-level logistics signature.",
    crew: "3",
    service: "In service",
    sort: 3,
  },
  {
    slug: "t-80bvm",
    blockSlug: "tanks",
    name: "T-80BVM",
    aka: "T-80BV modernisation",
    imageUrl: "/images/items/t-80bvm.jpg",
    imageCredit: "CC BY-SA 3.0 — Boevaya mashina",
    imagePage: "https://commons.wikimedia.org/wiki/File:T-80BVM_frontal_view_Army-2022.jpg",
    armament: "125 mm 2A46M-4; 12.7 mm NSVT",
    rangeText: "Gun to 3,000 m; Refleks-M ATGM 5,000 m",
    cues: [
      "Relikt ERA in large rectangular panels across the turret face",
      "Flat turbine rear deck with the central exhaust",
      "Sosna-U sight box, similar to the T-72B3M",
      "Slat armour over the engine deck",
    ],
    placements: ["Tank battalions of the Northern Fleet and selected first-line brigades"],
    doctrineNote: "Modernised turbine tank; concentrated rather than widely distributed.",
    crew: "3",
    service: "Current, modernised",
    sort: 4,
  },
  {
    slug: "t-90a",
    blockSlug: "tanks",
    name: "T-90A",
    aka: "Vladimir",
    imageUrl: "/images/items/t-90a.jpg",
    imageCredit: "CC BY-SA 4.0 — Vitaly V. Kuzmin",
    imagePage: "https://commons.wikimedia.org/wiki/File:T-90A_-_TankBiathlon2013-12.jpg",
    armament: "125 mm 2A46M-5; 12.7 mm remote station; Shtora",
    rangeText: "Gun 3,000 m; Refleks ATGM 5,000 m",
    cues: [
      "Welded turret with straight vertical sides (cast on earlier T-90)",
      "Shtora infrared dazzlers — two 'red eyes' either side of the gun",
      "T-72 style six-roadwheel running gear",
      "Kontakt-5 ERA integrated into the turret face",
    ],
    placements: ["Tank battalions of selected first-line brigades and divisions"],
    doctrineNote:
      "A refined T-72 lineage tank; the Shtora emitters are the fastest recognition cue.",
    crew: "3",
    service: "In service",
    sort: 5,
  },
  {
    slug: "t-90m",
    blockSlug: "tanks",
    name: "T-90M Proryv",
    aka: "Proryv-3",
    imageUrl: "/images/items/t-90m.jpg",
    imageCredit: "CC BY 4.0 — Ministry of Defence of the Russian Federation",
    imagePage: "https://commons.wikimedia.org/wiki/File:T-90M.jpg",
    armament: "125 mm 2A46M-5; 7.62 mm and 12.7 mm remote weapon station",
    rangeText: "Gun 3,000 m; Refleks-M ATGM 5,000 m",
    cues: [
      "Large square turret bustle rack at the rear",
      "Relikt ERA panels and slat cage over the rear",
      "Remote weapon station on the commander's cupola — no exposed 12.7 mm mount",
      "No Shtora dazzlers",
    ],
    placements: ["The most capable tank in first-line tank battalions; issued in limited numbers"],
    doctrineNote:
      "Priority equipment. Its presence indicates a formation the command considers a main effort.",
    crew: "3",
    service: "Current, priority issue",
    sort: 6,
  },
  {
    slug: "t-14",
    blockSlug: "tanks",
    name: "T-14 Armata",
    aka: "Obyekt 148",
    imageUrl: "/images/items/t-14.jpg",
    imageCredit: "CC BY-SA 4.0 — Kirill Borisenko",
    imagePage:
      "https://commons.wikimedia.org/wiki/File:T-14_%22Armata%22_during_%22Armiya_2020%22_exhibition.jpg",
    armament: "125 mm 2A82-1M in an unmanned turret; 12.7 mm remote station",
    rangeText: "Gun to 4,000 m+; ATGM to 8,000 m (claimed)",
    cues: [
      "Unmanned, slab-sided angular turret with no crew hatches",
      "Seven roadwheels — one more than the T-72/T-90",
      "Crew capsule in the hull front, hatches on the glacis",
      "Panoramic sensor masts on the turret roof",
    ],
    placements: ["Test and evaluation batches; not in general brigade service"],
    doctrineNote:
      "Doctrinally advertised, operationally marginal. Recognise it, but do not expect it in a line unit.",
    crew: "3",
    service: "Trials / limited",
    sort: 7,
  },
  {
    slug: "bmpt",
    blockSlug: "tanks",
    name: "BMPT Terminator",
    aka: "Obyekt 199 Ramka",
    imageUrl: "/images/items/bmpt.jpg",
    imageCredit: "CC BY-SA 3.0 — Boevaya mashina",
    imagePage: "https://commons.wikimedia.org/wiki/File:BMPT_Terminator_at_Army_2022.jpg",
    armament: "Twin 30 mm 2A42; 4x Ataka ATGM; 2x AG-17D grenade launchers",
    rangeText: "30 mm 4,000 m; Ataka 6,000 m; AGL 1,700 m",
    cues: [
      "Two 30 mm barrels side by side — unique in Russian service",
      "Twin ATGM tubes mounted outboard on each side of the turret",
      "T-72 hull and running gear",
      "Very low, wide turret with no main gun",
    ],
    placements: ["Tank support companies attached to selected tank regiments"],
    doctrineNote:
      "Built for urban and close terrain where tanks lack elevation and volume of fire.",
    crew: "5",
    service: "Limited service",
    sort: 8,
  },
];

/** Blocks authored after the first release, kept in their own modules. */
export const items: Item[] = [
  ...baseItems,
  ...heavyWeapons,
  ...lightVehicles,
  ...trucks,
  ...artillery,
  ...ifv,
  ...apc,
  ...ew,
  ...c2,
  ...radars,
  ...engineering,
  ...airDefence,
  ...recon,
  ...vessels,
  ...submarines,
  ...drones,
  ...aircraft,
];
