/**
 * Self-host the two webfonts.
 *
 *   bun run scripts/fonts.ts
 *
 * Fetches the stylesheet Google would have served the browser, downloads every
 * woff2 it points at into public/fonts/, and writes public/fonts/fonts.css with
 * the same @font-face rules rewritten to local paths.
 *
 * Both faces are SIL Open Font Licence, which permits redistribution; the
 * licence text is downloaded alongside them.
 *
 * The subsets matter for this app specifically. Estonian's õ ä ö ü live in
 * Latin-1, but the transliterated Russian names — Šilka, Kalašnikov, Štora —
 * need Š and Ž from Latin Extended-A, so latin-ext is not optional here.
 */
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap";

// Google serves woff2 only to a user agent it believes supports it.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const OUT_DIR = "public/fonts";
const KEEP = new Set(["latin", "latin-ext"]);

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// The stylesheet is a run of @font-face blocks, each preceded by a comment
// naming its subset. Anything outside latin/latin-ext is dropped: Cyrillic and
// Vietnamese are a third of the bytes and this app never renders them.
const blocks = css.split("/* ").slice(1);
const kept: string[] = [];
const downloads = new Map<string, string>();

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf(" */")).trim();
  if (!KEEP.has(subset)) continue;

  const face = block.slice(block.indexOf("@font-face"));
  const url = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const family = face.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = face.match(/font-weight:\s*(\d+)/)?.[1];
  if (!url || !family || !weight) continue;

  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2`;
  downloads.set(name, url);
  kept.push(`/* ${subset} */\n` + face.replace(url, `/fonts/${name}`).trim());
}

for (const [name, url] of downloads) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} for ${name}`);
  const bytes = new Uint8Array(await res.arrayBuffer());
  await Bun.write(`${OUT_DIR}/${name}`, bytes);
  console.log(`${name.padEnd(36)} ${(bytes.byteLength / 1024).toFixed(0).padStart(4)}K`);
}

const header = `/* Generated by scripts/fonts.ts — do not edit by hand.
   Archivo and IBM Plex Mono, SIL Open Font Licence 1.1 (see OFL.txt).
   Served from this origin so the app makes no third-party request. */\n\n`;
await Bun.write(`${OUT_DIR}/fonts.css`, header + kept.join("\n\n") + "\n");

const ofl = await fetch("https://openfontlicense.org/documents/OFL.txt", {
  headers: { "User-Agent": UA },
});
if (ofl.ok) await Bun.write(`${OUT_DIR}/OFL.txt`, await ofl.text());
else console.log("note: could not fetch OFL.txt; add it by hand");

console.log(`\n${downloads.size} files, stylesheet written to ${OUT_DIR}/fonts.css`);
