/*
 * Service worker source. Not shipped as-is: scripts/build-sw.ts substitutes the
 * three __PLACEHOLDER__ values from the finished build and writes the result to
 * .output/public/sw.js, where the Workers ASSETS binding serves it at /sw.js
 * — root scope, which is what the manifest's "scope": "/" needs.
 *
 * Hand-written rather than generated by a plugin because this project builds
 * through nitro's cloudflare-module preset, which owns main/assets/no_bundle,
 * and because the repo already does its build-time work in single-purpose
 * scripts rather than in plugin configuration.
 *
 * Three caches, versioned independently on purpose:
 *
 *   shell  — hashed JS/CSS/fonts/icons. Tied to the build; replaced wholesale.
 *   pages  — SSR HTML. Also tied to the build, because a document from an older
 *            build references asset filenames this build has deleted.
 *   images — 202 photographs, ~47 MB. Versioned by the *contents* of the image
 *            directory instead, so an ordinary code deploy does not make a
 *            reader download 47 MB again, while replacing a photograph does.
 */

const SHELL_VERSION = "__SHELL_VERSION__";
const IMAGES_VERSION = "__IMAGES_VERSION__";
const PRECACHE = __PRECACHE__;

const SHELL_CACHE = `afa-shell-${SHELL_VERSION}`;
const PAGES_CACHE = `afa-pages-${SHELL_VERSION}`;
const IMAGES_CACHE = `afa-images-${IMAGES_VERSION}`;

/** Caches the page owns too, so it can fill them and report on them. */
const KNOWN = [SHELL_CACHE, PAGES_CACHE, IMAGES_CACHE];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) =>
      // addAll is atomic: one 404 would throw away the whole install, and a
      // half-installed shell is worse than none.
      cache.addAll(PRECACHE),
    ),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      for (const key of await caches.keys()) {
        if (key.startsWith("afa-") && !KNOWN.includes(key)) await caches.delete(key);
      }
      await self.clients.claim();
    })(),
  );
});

/** The page asks for this when the reader accepts an update. */
self.addEventListener("message", (event) => {
  if (event.data === "skip-waiting") self.skipWaiting();
});

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  if (hit) return hit;
  const response = await fetch(request);
  // Only successes are kept: a cached 404 would outlive the mistake that
  // produced it. There is no cross-origin case to guard against here — the
  // fetch handler has already refused anything not served from this origin.
  if (response.ok) await cache.put(request, response.clone());
  return response;
}

async function navigate(request) {
  const cache = await caches.open(PAGES_CACHE);
  try {
    const response = await fetch(request);
    if (response.ok) await cache.put(request, response.clone());
    return response;
  } catch (error) {
    // This URL if we have it. Deliberately not falling back to the cached "/"
    // for an unknown route: that document is the home page and would hydrate
    // against the wrong URL.
    const hit = await cache.match(request);
    if (hit) return hit;
    const offline = await caches.match("/offline.html", { cacheName: SHELL_CACHE });
    if (offline) return offline;
    throw error;
  }
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  // Anything not served from this origin — Supabase above all — is left alone,
  // so being offline fails the way the app already expects it to.
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(navigate(request));
    return;
  }
  if (url.pathname.startsWith("/images/")) {
    event.respondWith(cacheFirst(request, IMAGES_CACHE));
    return;
  }
  if (url.pathname.startsWith("/assets/") || url.pathname.startsWith("/fonts/")) {
    event.respondWith(cacheFirst(request, SHELL_CACHE));
  }
});
