/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as DrillFlashcardsRouteImport } from './routes/drill.flashcards'
import { Route as DrillPhotoIdRouteImport } from './routes/drill.photo-id'
import { Route as DrillStructureRouteImport } from './routes/drill.structure'
import { Route as ExamBlockRouteImport } from './routes/exam.$block'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnBlockIndexRouteImport } from './routes/learn.$block.index'
import { Route as LearnBlockItemRouteImport } from './routes/learn.$block.$item'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillFlashcardsRoute = DrillFlashcardsRouteImport.update({
  id: '/drill/flashcards',
  path: '/drill/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillPhotoIdRoute = DrillPhotoIdRouteImport.update({
  id: '/drill/photo-id',
  path: '/drill/photo-id',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillStructureRoute = DrillStructureRouteImport.update({
  id: '/drill/structure',
  path: '/drill/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamBlockRoute = ExamBlockRouteImport.update({
  id: '/exam/$block',
  path: '/exam/$block',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnBlockIndexRoute = LearnBlockIndexRouteImport.update({
  id: '/learn/$block/',
  path: '/learn/$block/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnBlockItemRoute = LearnBlockItemRouteImport.update({
  id: '/learn/$block/$item',
  path: '/learn/$block/$item',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/drill/flashcards': typeof DrillFlashcardsRoute
  '/drill/photo-id': typeof DrillPhotoIdRoute
  '/drill/structure': typeof DrillStructureRoute
  '/exam/$block': typeof ExamBlockRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$block/$item': typeof LearnBlockItemRoute
  '/learn/$block/': typeof LearnBlockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/drill/flashcards': typeof DrillFlashcardsRoute
  '/drill/photo-id': typeof DrillPhotoIdRoute
  '/drill/structure': typeof DrillStructureRoute
  '/exam/$block': typeof ExamBlockRoute
  '/learn': typeof LearnIndexRoute
  '/learn/$block/$item': typeof LearnBlockItemRoute
  '/learn/$block': typeof LearnBlockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/drill/flashcards': typeof DrillFlashcardsRoute
  '/drill/photo-id': typeof DrillPhotoIdRoute
  '/drill/structure': typeof DrillStructureRoute
  '/exam/$block': typeof ExamBlockRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$block/$item': typeof LearnBlockItemRoute
  '/learn/$block/': typeof LearnBlockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/progress'
    | '/reset-password'
    | '/review'
    | '/drill/flashcards'
    | '/drill/photo-id'
    | '/drill/structure'
    | '/exam/$block'
    | '/learn/'
    | '/learn/$block/$item'
    | '/learn/$block/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/progress'
    | '/reset-password'
    | '/review'
    | '/drill/flashcards'
    | '/drill/photo-id'
    | '/drill/structure'
    | '/exam/$block'
    | '/learn'
    | '/learn/$block/$item'
    | '/learn/$block'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/progress'
    | '/reset-password'
    | '/review'
    | '/drill/flashcards'
    | '/drill/photo-id'
    | '/drill/structure'
    | '/exam/$block'
    | '/learn/'
    | '/learn/$block/$item'
    | '/learn/$block/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  DrillFlashcardsRoute: typeof DrillFlashcardsRoute
  DrillPhotoIdRoute: typeof DrillPhotoIdRoute
  DrillStructureRoute: typeof DrillStructureRoute
  ExamBlockRoute: typeof ExamBlockRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnBlockItemRoute: typeof LearnBlockItemRoute
  LearnBlockIndexRoute: typeof LearnBlockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/flashcards': {
      id: '/drill/flashcards'
      path: '/drill/flashcards'
      fullPath: '/drill/flashcards'
      preLoaderRoute: typeof DrillFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/photo-id': {
      id: '/drill/photo-id'
      path: '/drill/photo-id'
      fullPath: '/drill/photo-id'
      preLoaderRoute: typeof DrillPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill/structure': {
      id: '/drill/structure'
      path: '/drill/structure'
      fullPath: '/drill/structure'
      preLoaderRoute: typeof DrillStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$block': {
      id: '/exam/$block'
      path: '/exam/$block'
      fullPath: '/exam/$block'
      preLoaderRoute: typeof ExamBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$block/': {
      id: '/learn/$block/'
      path: '/learn/$block'
      fullPath: '/learn/$block/'
      preLoaderRoute: typeof LearnBlockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$block/$item': {
      id: '/learn/$block/$item'
      path: '/learn/$block/$item'
      fullPath: '/learn/$block/$item'
      preLoaderRoute: typeof LearnBlockItemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  DrillFlashcardsRoute: DrillFlashcardsRoute,
  DrillPhotoIdRoute: DrillPhotoIdRoute,
  DrillStructureRoute: DrillStructureRoute,
  ExamBlockRoute: ExamBlockRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnBlockItemRoute: LearnBlockItemRoute,
  LearnBlockIndexRoute: LearnBlockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
